org.postgresql.util.PSQLException: A tentativa de conex√£o falhou.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:137)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:124)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:386)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at academia.DAO.ConnectionDatabase.<init>(ConnectionDatabase.java:75)
	at academia.DAO.ConnectionDatabase.getInstance(ConnectionDatabase.java:95)
	at academia.DAO.FingerprintDAO.takeConnection(FingerprintDAO.java:47)
	at academia.DAO.FingerprintDAO.<init>(FingerprintDAO.java:40)
	at academia.controller.BiometricReaderController.<init>(BiometricReaderController.java:49)
	at academia.controller.ThreadDeviceController.start(ThreadDeviceController.java:67)
	at academia.Main.main(Main.java:44)
Caused by: java.net.UnknownHostException: localhos
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:77)
	... 15 more
